# Generated by Django 4.0.5 on 2022-06-02 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project_1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
